<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-QKCURUKN" failures="3" tests="15" name="com.quantum.LoginTestCases" time="142.878" errors="0" timestamp="2024-08-23T21:43:30 IST" skipped="0">
  <testcase classname="com.quantum.LoginTestCases" name="testHomeLinkIsDisplayed" time="10.645"/>
  <testcase classname="com.quantum.LoginTestCases" name="testSignupLinkIsDisplayed" time="9.646"/>
  <testcase classname="com.quantum.LoginTestCases" name="testLoginLinkNavigatesToLoginPage" time="15.241"/>
  <testcase classname="com.quantum.LoginTestCases" name="testSignupLinkNavigatesToSignupPage" time="15.376"/>
  <testcase classname="com.quantum.LoginTestCases" name="testPageTitle" time="10.086">
    <failure message="Cannatrader expected:&lt;Cannatrader&gt; but was:&lt;Page title does not match!&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Cannatrader expected:<Cannatrader> but was:<Page title does not match!>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.quantum.LoginTestCases.testPageTitle(LoginTestCases.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testPageTitle -->
  <testcase classname="com.quantum.LoginTestCases" name="testEmailFieldPresence" time="4.158"/>
  <testcase classname="com.quantum.LoginTestCases" name="testPasswordFieldPresence" time="6.385"/>
  <testcase classname="com.quantum.LoginTestCases" name="testForgotPasswordLink" time="6.636"/>
  <testcase classname="com.quantum.LoginTestCases" name="testSignUpLink" time="2.971"/>
  <testcase classname="com.quantum.LoginTestCases" name="testEmailFieldAcceptsInput" time="10.650">
    <failure message="test@example.com expected:&lt;test@example.com&gt; but was:&lt;Email input is not accepted!&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: test@example.com expected:<test@example.com> but was:<Email input is not accepted!>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.quantum.LoginTestCases.testEmailFieldAcceptsInput(LoginTestCases.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testEmailFieldAcceptsInput -->
  <testcase classname="com.quantum.LoginTestCases" name="testPasswordFieldAcceptsInput" time="8.227">
    <failure message="password123 expected:&lt;password123&gt; but was:&lt;Password input is not accepted!&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: password123 expected:<password123> but was:<Password input is not accepted!>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.quantum.LoginTestCases.testPasswordFieldAcceptsInput(LoginTestCases.java:140)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testPasswordFieldAcceptsInput -->
  <testcase classname="com.quantum.LoginTestCases" name="testEmailFieldPlaceholder" time="5.662"/>
  <testcase classname="com.quantum.LoginTestCases" name="testPasswordFieldPlaceholder" time="7.229"/>
  <testcase classname="com.quantum.LoginTestCases" name="Loginwithinvalidcred" time="13.186"/>
  <testcase classname="com.quantum.LoginTestCases" name="SuccessfulLogin" time="16.780"/>
</testsuite> <!-- com.quantum.LoginTestCases -->
